# scripts/lhd/policy_catalog.py


from __future__ import annotations
from typing import Dict, Any

from scripts.lhd.algorithms_state import (
    IsolateNewCases,
    TraceNewCases,
    TestContactsOfKnownCases,
    TraceEdgeEndpoints,
    IsolateNeighborsOfHighDegreeCases,
)
from scripts.lhd.planner import GreedyPlanner

# --- LHD Algorithms: How they work and what they emulate ---
# LHD algorithms are the atomic units of intervention. Each algorithm analyzes the LHD's
# current knowledge (LHDState) and proposes specific actions (ActionProposal) for individuals.

# IsolateNewCases:
#   Computational: Iterates through `state.new_cases_today` (a NumPy array of node IDs).
#                  For each newly reported case, it creates an `ActionProposal` to "isolate" that node.
#                  The priority and cost are configurable.
#   LHD Emulation: Represents the LHD's immediate, reactive response to a newly reported
#                  case by initiating isolation measures for that individual. This is a
#                  fundamental public health intervention to prevent further spread from
#                  known infected individuals.

# TraceNewCases:
#   Computational: Similar to `IsolateNewCases`, it iterates through `state.new_cases_today`.
#                  For each newly reported case, it creates an `ActionProposal` to "trace" that node.
#                  The priority and cost are configurable.
#   LHD Emulation: Represents the LHD's action of initiating contact tracing for newly
#                  reported cases. This aims to identify and notify individuals who may
#                  have been exposed, allowing for further interventions like testing or quarantine.

# TestContactsOfKnownCases:
#   Computational: Iterates through `state.known_case_list`. For each known case, it retrieves
#                  its known neighbors from `state.known_adj`. For each neighbor, if they are
#                  not already a known case and not already pending a test, it creates an
#                  `ActionProposal` to "test" that neighbor.
#   LHD Emulation: Emulates the LHD's strategy of testing contacts of confirmed cases. This is a
#                  proactive measure to detect secondary cases early, even if they are asymptomatic,
#                  and prevent further transmission.

# TraceEdgeEndpoints:
#   Computational: Looks at `state.known_edges` (edges discovered through tracing). Specifically,
#                  it focuses on `new_edges_today` (edges discovered in the current time step).
#                  For each endpoint of these newly discovered edges, if that endpoint is not
#                  already a known case, it creates an `ActionProposal` to "trace" that node.
#   LHD Emulation: Represents a "network crawling" or "forward tracing" strategy. After discovering
#                  a contact (an edge), the LHD extends its investigation to the newly identified
#                  individual (the endpoint of the edge) to find *their* contacts, thereby expanding
#                  the known contact network.

# IsolateNeighborsOfHighDegreeCases:
#   Computational: Identifies `state.new_cases_today`. For each new case, it calculates its
#                  "known degree" (number of known contacts in `state.known_adj`). It then sorts
#                  these new cases by degree (highest first). For a selected subset (implicitly,
#                  based on capacity and priority), it proposes to "isolate" all known neighbors
#                  of these high-degree cases.
#   LHD Emulation: This policy targets individuals who are likely to be "super-spreaders" or highly
#                  connected within the known network. By isolating their contacts, the LHD aims
#                  to disrupt transmission from potentially high-impact individuals, even if those
#                  contacts are not yet symptomatic or confirmed cases. This is a targeted, risk-based intervention.

# Registry of algorithms currently implemented
ALGO_REGISTRY = {
    "isolate_new_cases": IsolateNewCases,
    "trace_new_cases": TraceNewCases,
    "test_contacts_of_known_cases": TestContactsOfKnownCases,
    "trace_edge_endpoints": TraceEdgeEndpoints,
    "isolate_neighbors_of_high_degree_cases": IsolateNeighborsOfHighDegreeCases,
}

# Registry of planners currently implemented
PLANNER_REGISTRY = {
    "greedy": GreedyPlanner,
}

# --- LHD Policies: Combinations of algorithms and their overall strategy ---
# LHD policies combine one or more algorithms to form a comprehensive intervention strategy.
# The planner (e.g., GreedyPlanner) then allocates daily LHD capacity among the proposals
# generated by these algorithms, prioritizing actions based on their assigned scores.


# LHD Policies, which are combinations of algorithms (prioritizing individuals) and planners (resource allocation strategies)
POLICIES: Dict[str, Dict[str, Any]] = {
    "observe_only": {
        "planner": "greedy",
        "algorithms": [],
        "description": (
            "Computational: No algorithms are active, so no ActionProposals are generated. "
            "The LHD simply processes surveillance data without initiating any interventions.\n"
            "LHD Emulation: Represents a baseline scenario where the LHD has no active intervention "
            "capacity or chooses not to intervene beyond passive surveillance. This is often used "
            "as a control group for comparison."
        ),
    },
    "isolate_only": {
        "planner": "greedy",
        "algorithms": [
            ("isolate_new_cases", {}),
        ],
        "description": (
            "Computational: Only the 'IsolateNewCases' algorithm generates proposals. The planner "
            "will prioritize isolating newly reported cases based on available capacity.\n"
            "LHD Emulation: Focuses solely on isolating individuals once they are confirmed cases. "
            "This is a reactive strategy that aims to contain spread from known infections but "
            "does not proactively seek out contacts."
        ),
    },
    "trace_only": {
        "planner": "greedy",
        "algorithms": [
            ("trace_new_cases", {}),
        ],
        "description": (
            "Computational: Only the 'TraceNewCases' algorithm generates proposals. The planner "
            "will prioritize tracing newly reported cases based on available capacity.\n"
            "LHD Emulation: Focuses solely on contact tracing for newly reported cases. The LHD "
            "invests resources in identifying and notifying contacts, but does not directly "
            "isolate or test them (unless other policies are combined)."
        ),
    },
    "trace_then_isolate": {
        "planner": "greedy",
        "algorithms": [
            ("trace_new_cases", {}),
            ("isolate_new_cases", {}),
        ],
        "description": (
            "Computational: Both 'TraceNewCases' and 'IsolateNewCases' algorithms generate proposals. "
            "By default, 'IsolateNewCases' typically has a higher priority, meaning newly reported "
            "cases would first be isolated, and then traced, subject to daily capacity.\n"
            "LHD Emulation: A common public health strategy where confirmed cases are immediately "
            "isolated, and then their contacts are traced to identify and manage potential secondary cases."
        ),
    },
    "trace_and_test": {
        "planner": "greedy",
        "algorithms": [
            ("isolate_new_cases", {"priority": 2.0}),  # Highest priority
            ("trace_new_cases", {"priority": 1.5}),
            ("test_contacts_of_known_cases", {"priority": 1.0}),
        ],
        "description": (
            "Computational: 'IsolateNewCases', 'TraceNewCases', and 'TestContactsOfKnownCases' "
            "algorithms generate proposals. 'IsolateNewCases' has the highest priority, followed "
            "by 'TraceNewCases', and then 'TestContactsOfKnownCases'. This means newly reported "
            "cases are isolated, then traced, and then known contacts of *any* known case "
            "(including those found through tracing) are tested, all within daily capacity limits.\n"
            "LHD Emulation: An aggressive strategy that combines isolation of confirmed cases, "
            "tracing of their contacts, and proactive testing of those contacts. This aims for "
            "rapid identification and containment of infections within the contact network."
        ),
    },
    "network_crawl": {
        "planner": "greedy",
        "algorithms": [
            ("trace_new_cases", {}),
            ("trace_edge_endpoints", {}),
        ],
        "description": (
            "Computational: 'TraceNewCases' proposes tracing newly reported cases. "
            "'TraceEdgeEndpoints' then proposes tracing the individuals identified as contacts "
            "from *those* traces (or any other newly discovered edges), effectively expanding "
            "the LHD's knowledge of the network.\n"
            "LHD Emulation: This policy emphasizes expanding the LHD's knowledge of the contact "
            "network. It starts with tracing known cases and then 'crawls' outwards by tracing "
            "the contacts of those contacts, aiming to map out the transmission chains more extensively."
        ),
    },
    "network_crawl_isolate": {
        "planner": "greedy",
        "algorithms": [
            ("trace_edge_endpoints", {}),
            ("isolate_new_cases", {"priority": 2.0}),
            ("isolate_neighbors_of_high_degree_cases", {"priority": 1.5}),
        ],
        "description": (
            "Computational: 'IsolateNewCases' and 'IsolateNeighborsOfHighDegreeCases' focus on "
            "isolation, while 'TraceEdgeEndpoints' focuses on expanding knowledge. 'IsolateNewCases' "
            "has the highest priority, followed by 'IsolateNeighborsOfHighDegreeCases', and then "
            "'TraceEdgeEndpoints'. This prioritizes immediate isolation of new cases and their "
            "high-impact contacts, while also continuously improving the LHD's understanding of "
            "the outbreak's structure.\n"
            "LHD Emulation: A hybrid strategy that combines aggressive isolation of new cases and "
            "their high-degree contacts with a network-crawling approach to expand knowledge. This "
            "aims to quickly reduce transmission from key individuals while continuously improving "
            "the LHD's understanding of the outbreak's structure."
        ),
    },
}


def build_policy(policy_name: str, *, default_algo_params: dict) -> tuple[list, object]:
    name = str(policy_name or "observe_only")
    spec = POLICIES.get(name, POLICIES["observe_only"])

    planner_cls = PLANNER_REGISTRY[spec.get("planner", "greedy")]
    planner = planner_cls()

    algos = []
    for algo_name, params in spec.get("algorithms", []):
        cls = ALGO_REGISTRY[algo_name]

        # Get the default configuration for this algorithm (cost, priority, and action-specific params)
        algo_config = default_algo_params.get(algo_name, {})
        # Policy-specific overrides (from POLICIES dict) can be merged here if needed, but currently 'params' is empty.
        algo_params = {
            **algo_config,
            **params,
        }  # Merge policy-specific params (if any) over defaults
        algos.append(cls(**algo_params))

    return algos, planner, name
