%%% This script plots PRCC vs time plots for various outputs and PRCC
%%% calculation methods. Before using this script, an LHS run and 
%%% corresponding prcc analyses should be done using LHSPRCCfromCSV.m
%%%
%%% INPUT
%%% path: The full path as a string where the prcc file (prccResultsFile) is located.
%%% 
%%% prccResultsFile: The mat file generated by the script lhsPrccFromCsv.m.
%%% 
%%% prccThreshold: the threshold value to show prcc results. For example,
%%% if prccThreshold is 0.1, then the prcc values between -0.1 and 0.1 are
%%% not shown in the plots.
%%%
%%% output_names (optional): a cell array with the names of the outputs 
%%% to do the PRCC analysis for. If nothing specified, then the code takes
%%% all the outputs available in the prccResultsFile.
%%% Example: output_names = {'"Int.Mtb."','"repExtMtb"'}; % note the quotes
%%%
%%% prcc_method (optional): a vector with numbers 1-4 where each number
%%% stands for a prcc calculation method.
%%%     1: uncorrected prcc values
%%%     2: uncorrected prcc values with z-test significance
%%%     3: bonferroni-corrected prcc values
%%%     4: bhfdr-corrected prcc values
%%% If nothing specified, then the code plots all available prcc
%%% calculation methods.
%%% Example: prcc_method = [1 3]; % this plots uncorrected and bonferroni
%%% prcc values
%%%
%%% OUTPUT
%%% A figure with (numel(prcc_method)) x (numel(output_names)) panels.
%%% Each row represent a prcc calculation method. If no prcc_method is
%%% specified, we have 4 rows such as:
%%%     row 1: uncorrected prcc values
%%%     row 2: uncorrected prcc values with z-test significance
%%%     row 3: bonferroni-corrected prcc values
%%%     row 4: bhfdr-corrected prcc values
%%% Each column represents prcc values for a certain output.
%%% The figure is saved as a png in the directory where the prcc mat file
%%% is located (path).

function plotPRCC(path, prccResultFile, prccThreshold, options)

    arguments
       path {mustBeNonzeroLengthText}
       prccResultFile {mustBeNonzeroLengthText}
       prccThreshold {mustBeNumeric}
       options.output_names {mustBeA(options.output_names, "cell"), mustBeNonzeroLengthText}
       options.prcc_method {mustBeInteger, mustBeVector}
       options.time_steps_per_day (1,1) double = 1
    end

    unwrap_struct(options); %#ok<*NODEF>

    % Load prcc mat file
    prccResult = loadTheMatFile(prccResultFile, path);

    if exist('output_names', 'var')
        check_output_names(output_names, prccResult.modelOutputNames);
    else
        output_names = prccResult.modelOutputNames;
    end

    full_prcc_method = [1, 2, 3, 4];
    if exist('prcc_method', 'var')
        check_prcc_method(prcc_method, full_prcc_method);        
    else
        prcc_method = full_prcc_method;
    end
    
    % Create an array with uncorrected prcc values where non-significant
    % entries are masked with 1 based on a PCC Z-test.
    uncorrectedPccZtestSignificantPrcc = generatePccZtestSignificantPrcc(prccResult);
    
    % Update prccResult so that the parameters that have no significant 
    % prccs are removed. This makes the plot legend simpler. This also 
    % removes the unwanted outputs based on output_names.
    updatedPrccResult = updatePrcc(prccResult, uncorrectedPccZtestSignificantPrcc, prccThreshold, output_names, prcc_method);

    % Using updatedPrccResult, create an array with uncorrected prcc values 
    % where non-significant entries are masked with 1 based on a PCC
    % Z-test.
    uncorrectedPccZtestSignificantPrcc_updated = generatePccZtestSignificantPrcc(updatedPrccResult);

    % Create tiled figure.
    nrOutput = numel(updatedPrccResult.modelOutputNames);
    nrPrccMethod = numel(prcc_method);

    % Only plot the title for the first row - for the first PRCC method
    % specified.
    plotTitleIdx = prcc_method(1);

    t = tiledlayout(nrPrccMethod, nrOutput, 'TileIndexing', ...
                   'columnmajor', 'Padding', 'tight');
    t.Units = 'inches';
    t.OuterPosition = [0 0 7.5 5];
    xlabel(t, 'Time (days)', 'FontName', 'Times', 'FontSize', 12)
    ylabel(t, 'PRCC', 'FontName', 'Times', 'FontSize', 12)

    % Create each column of plots, one column of plots per output.
    % Each column of plots has a a tile for each selected PRCC method to
    % include.
    for i = 1:nrOutput

        % Plot uncorrected PRCC values if specified in prcc_method.
        if ismember(1, prcc_method)
            if plotTitleIdx == 1
                plotTitle = true;
            else
                plotTitle = false;
            end
            uncorr_sign_i = squeeze(updatedPrccResult.uncorrectedSignificantPrcc(:,i,:));
            t = plotPRCCPanel(t, i, uncorr_sign_i, ...
                    updatedPrccResult.analysisTimePoints, 144, ...
                    updatedPrccResult.paramNames, ...
                    updatedPrccResult.modelOutputNames{i}, prccThreshold, ...
                    'Uncorrected', plotTitle);
        end

        % If specified in prcc_method, plot uncorrected PRCC values where 
        % unsignificant values are masked based on the PCC Z-test.
        if ismember(2, prcc_method)
            if plotTitleIdx == 2
                plotTitle = true;
            else
                plotTitle = false;
            end            
            uncorr_ztest_i = squeeze(uncorrectedPccZtestSignificantPrcc_updated(:,i,:));
            t = plotPRCCPanel(t, i, uncorr_ztest_i, ...
                    updatedPrccResult.analysisTimePoints, 144, ...
                    updatedPrccResult.paramNames, ...
                    updatedPrccResult.modelOutputNames{i}, prccThreshold, ...
                    'Z-test', plotTitle);
        end

        % Plot bonferroni-corrected PRCC values if specified in
        % prcc_method.
        if ismember(3, prcc_method)
            if plotTitleIdx == 3
                plotTitle = true;
            else
                plotTitle = false;
            end            
            bonferroni_sign_i = squeeze(updatedPrccResult.bonferroniSignificantPrcc(:,i,:));
            t = plotPRCCPanel(t, i, bonferroni_sign_i, ...
                    updatedPrccResult.analysisTimePoints, 144, ...
                    updatedPrccResult.paramNames, ...
                    updatedPrccResult.modelOutputNames{i}, prccThreshold, ...
                    'Bonferroni', plotTitle);
        end

        % Plot bhfdr-corrected PRCC values if speciprccResult.modelOutputNamesfied in prcc_method.
        if ismember(4, prcc_method)
            if plotTitleIdx == 4
                plotTitle = true;
            else
                plotTitle = false;
            end            
            bhfdr_sign_i = squeeze(updatedPrccResult.bhfdrSignificantPrcc(:,i,:));
            t = plotPRCCPanel(t, i, bhfdr_sign_i, ...
                    updatedPrccResult.analysisTimePoints, 144, ...
                    updatedPrccResult.paramNames, ...
                    updatedPrccResult.modelOutputNames{i}, prccThreshold, ...
                    'Bhfdr', plotTitle);
        end

    end % for i = 1:nrOutput

    % Add a common legend.
    leg = legend(updatedPrccResult.paramNames, 'NumColumns', 3);
    leg.Layout.Tile = 'north';    

    % Save figure. Maximize the figure window, so when it gets saved the
    % full set of tiles are visible in the saved file.
    fig = gcf;
    fig.WindowState = 'maximized';
    %fig.Visible = 'off';
    full_path = strcat(path, '/prcc_threshold', num2str(prccThreshold), '.png');
    fprintf('Saving the figure to file:\n%s\n', full_path)
    fprintf('\n!!! Do not adjust the figure window !!!\n')
    exportgraphics(gcf, full_path, 'Resolution', 600)
    close all

end

function check_output_names(output_names, all_model_output_names)
    % output_names were specified, check them for validity.
    if isempty(output_names)
        error("No output names were specified.\n")
    end

    [~, idx_output] = ismember(output_names, all_model_output_names);

    unmatched_idx = find(idx_output == 0);
    unmatched_count = numel(unmatched_idx);
    if unmatched_count > 0
        fmt = "%d specified output names";
        fmt = fmt + " do not match any model output names from the prcc";
        fmt = fmt + " result file:\n";
        for i = 1:unmatched_count
            fmt = fmt + output_names{unmatched_idx(i)} + " ";
        end
        error(fmt, unmatched_count)
    end
end % function check_output_names

function check_prcc_method(prcc_method, full_prcc_method)
    % If prcc_method is specified check it for validity.
    % If prcc_method is not specified, plot all prcc calculation methods.
    prcc_method_count = numel(prcc_method);
    if prcc_method_count == 0
        error("An empty prcc method vector was specified.\n")
    elseif prcc_method_count > 4
        error("Too many prcc methods specified: %d\n", prcc_method_count)
    else
        [~, idx_method] = ismember(prcc_method, full_prcc_method);
        unmatched_idx = find(idx_method == 0);
        unmatched_count = numel(unmatched_idx);
        if unmatched_count > 0
            fmt = "%d specified PRCC methods do not match any valid";
            fmt = fmt + " PRCC methods:\n";
            for i = 1:unmatched_count
                fmt = fmt + prcc_method(unmatched_idx(i)) + " ";
            end
            error(fmt, unmatched_count)
        end
    end

    % Check for duplicates.
    [~, first_idx] = unique(prcc_method, 'stable');
    dup_idx = setdiff(1:numel(prcc_method), first_idx);
    dup_count = numel(dup_idx);
    if dup_count > 0
        fmt = "%d duplicate PRCC methods:\n";
        for i = 1:dup_count
            fmt = fmt + num2str(prcc_method(dup_idx(i))) + " ";
        end
        error(fmt, dup_count)
    end
end % function prcc_method

% Create an array with uncorrected prcc values where non-significant
% entries are masked with 1 based on a PCC Z-test.
function PccZtestSignificantPrcc = generatePccZtestSignificantPrcc(prccResult)
    PccZtestSignificantPrcc = prccResult.uncorrectedPrcc;
    PccZtestSignificantPrcc(prccResult.uncorrectedPccZtest == 0) = 1;
    PccZtestSignificantPrcc(isnan(PccZtestSignificantPrcc)) = 1;
end

% Update prccResult object so that unsignificant parameters are removed.
function updatedPrccResult = updatePrcc(...
    prccResult, uncorrectedPccZtestSignificantPrcc, prccThreshold, ...
    output_names, prcc_method)

    % Find the indexes of desired outputs.
    [~, idx_output] = ismember(output_names, prccResult.modelOutputNames);

    % Combine prcc arrays based on the specified prcc methods and outputs.
    prcc_arrays_combined = combinePrccArrays(prccResult, uncorrectedPccZtestSignificantPrcc, idx_output, prcc_method);
    
    % Convert ones (label for unsignificant values) and values above the
    % threshold to NaNs to remove from the plot.
    prcc_arrays_combined = convertOnesAndThresholdsToNans(prcc_arrays_combined, prccThreshold, 'convertThreshold'); 

    % Find the indexes of parameters that have at least one non-nan value.
    idx_nonNan = findAllNonNanParamIdx(prcc_arrays_combined);
    
    % Update the struct
    updatedPrccResult = updateStruct(prccResult, idx_nonNan, idx_output);

end

% Combine prcc arrays based on the specified prcc methods and outputs.
function prcc_arrays_combined = combinePrccArrays(...
    prccResult, uncorrectedPccZtestSignificantPrcc, idx_output, prcc_method)

    % Take prcc arrays based on the indices of desired outputs.
    uncorrectedPrcc = prccResult.uncorrectedSignificantPrcc(:,idx_output,:);
    uncorrectedPccZtestPrcc = uncorrectedPccZtestSignificantPrcc(:,idx_output,:);
    bonferroniPrcc = prccResult.bonferroniSignificantPrcc(:,idx_output,:);
    bhfdrPrcc = prccResult.bhfdrSignificantPrcc(:,idx_output,:);

    % Flatten prcc arrays so that the prcc values of each parameter is in
    % a column.
    uncorrectedPrcc_flattened = reshape(uncorrectedPrcc, [], size(uncorrectedPrcc, 3));
    uncorrectedPccZtestPrcc_flattened = reshape(uncorrectedPccZtestPrcc, [], size(uncorrectedPccZtestPrcc, 3));
    bonferroniPrcc_flattened = reshape(bonferroniPrcc, [], size(bonferroniPrcc, 3));
    bhfdrPrcc_flattened = reshape(bhfdrPrcc, [], size(bhfdrPrcc, 3));

    % Combine prcc array with all calculation methods
    prcc_arrays_combined_all = cat(3, uncorrectedPrcc_flattened, uncorrectedPccZtestPrcc_flattened, bonferroniPrcc_flattened, bhfdrPrcc_flattened);

    % Take only the values for prcc calculation methods specified in
    % prcc_method.
    prcc_arrays_combined = prcc_arrays_combined_all(:,:,prcc_method);
end


% Update the struct based on the indexes of parameters with non-nan prcc
% values and desired outputs.
function updatedPrccResult = updateStruct(prccResult, idx_nonNan, idx_output)

    updatedPrccResult = prccResult;
    
    updatedPrccResult.lhsMatrix = prccResult.lhsMatrix(:,idx_nonNan);
    updatedPrccResult.modelOutput = prccResult.modelOutput(idx_output,:,:);
    updatedPrccResult.modelOutputNames = prccResult.modelOutputNames(idx_output);    
    updatedPrccResult.paramNames = prccResult.paramNames(idx_nonNan);
    updatedPrccResult.uncorrectedPrcc = prccResult.uncorrectedPrcc(:,idx_output,idx_nonNan);
    updatedPrccResult.uncorrectedSignificance = prccResult.uncorrectedSignificance(:,idx_output,idx_nonNan);
    updatedPrccResult.uncorrectedPccZtest = prccResult.uncorrectedPccZtest(:,idx_output,idx_nonNan);
    updatedPrccResult.uncorrectedPccZtestSignificance = prccResult.uncorrectedPccZtestSignificance(:,idx_output,idx_nonNan);
    updatedPrccResult.uncorrectedSignificantPrcc = prccResult.uncorrectedSignificantPrcc(:,idx_output,idx_nonNan);
    updatedPrccResult.uncorrectedSignificantSignificance = prccResult.uncorrectedSignificantSignificance(:,idx_output,idx_nonNan);
    updatedPrccResult.bonferroniSignificance = prccResult.bonferroniSignificance(:,idx_output,idx_nonNan);
    updatedPrccResult.bonferroniSignificantPrcc = prccResult.bonferroniSignificantPrcc(:,idx_output,idx_nonNan);
    updatedPrccResult.bonferroniSignificantSignifcance = prccResult.bonferroniSignificantSignifcance(:,idx_output,idx_nonNan);
    updatedPrccResult.bhfdrSignificance = prccResult.bhfdrSignificance(:,idx_output,idx_nonNan);
    updatedPrccResult.bhfdrSignificantPrcc = prccResult.bhfdrSignificantPrcc(:,idx_output,idx_nonNan);
    updatedPrccResult.bhfdrSignificantSignificance = prccResult.bhfdrSignificantSignificance(:,idx_output,idx_nonNan);
    
end

% Find the indexes of parameters that has at least one non-nan prcc value.
function idx_nonNan = findAllNonNanParamIdx(prcc_array)

    nrParams = size(prcc_array, 2);
    markAllNonNans = ones(nrParams, 1);
    for i = 1:nrParams
        prcc_param = prcc_array(:,i,:);

        if all(all(isnan(prcc_param)))
            markAllNonNans(i) = 0;
        end
    end    
    idx_nonNan = find(markAllNonNans);

end

% Modify prcc array so that unsignificant values and the values between the
% threshold boundaries are set to NaNs to prevent them from being visible 
% on the plot.
function prcc_array = convertOnesAndThresholdsToNans(prcc_array, prccThreshold, string_threshold)
    prcc_array(prcc_array == 1) = NaN;
    if strcmp(string_threshold, 'convertThreshold')
        prcc_array(prcc_array <= prccThreshold & prcc_array >= -1*prccThreshold) = NaN;
    end
end

% Plot PRCC vs time panels.
function t = plotPRCCPanel(t, outputNo, prcc_array, timePoints, ...
    time_steps_per_day, paramNames, outputName, prccThreshold, ylabel_name, plotTitle)

    nexttile
    cmap = hsv(numel(paramNames));
    set(gca, 'ColorOrder', cmap, 'NextPlot', 'add');
    prcc_array = convertOnesAndThresholdsToNans(prcc_array, prccThreshold, 'keepThreshold');

    adjusted_time_points = timePoints / options.time_steps_per_day;

    plot(adjusted_time_points, prcc_array, 'LineWidth', 1)

    ylim([-1 1])

    % Define X axis and its labels based on the actual time points, in
    % days.
    min_x = adjusted_time_points(1) - 5;
    max_x = adjusted_time_points(end);
    mid_x = min_x + (max_x - min_x) / 2;

    xlim([min_x max_x])
    xticks([min_x mid_x max_x])
    xticklabels([min_x mid_x max_x])

    if outputNo == 1
        ylabel(ylabel_name)
    end
    set(gca, 'FontSize', 8, 'FontName', 'Times')

    if plotTitle
        title(outputName, 'FontSize', 4)
    end

end

% Load the mat file with the struct where prcc values are stored.
function data = loadTheMatFile(fileName, dir)
    file = load(strcat(dir, '/', fileName));
    varName = fieldnames(file);
    data = file.(varName{1});
end
